from typing import Union, Literal, List
from hangar_sdk.core.rbac.aws.base_type import GenericResourceType
from hangar_sdk.resources.terraform import AbstractTerraformResource

aws_macie2_privilege_type = Union[Literal["UpdateResourceProfileDetections"], Literal["GetUsageStatistics"], Literal["UpdateRevealConfiguration"], Literal["GetInvitationsCount"], Literal["GetAllowList"], Literal["CreateSampleFindings"], Literal["PutClassificationExportConfiguration"], Literal["DisassociateFromMasterAccount"], Literal["ListResourceProfileDetections"], Literal["GetResourceProfile"], Literal["GetFindingsFilter"], Literal["ListAllowLists"], Literal["DeleteMember"], Literal["TagResource"], Literal["GetAdministratorAccount"], Literal["DescribeOrganizationConfiguration"], Literal["ListSensitivityInspectionTemplates"], Literal["DescribeClassificationJob"], Literal["UpdateAutomatedDiscoveryConfiguration"], Literal["ListResourceProfileArtifacts"], Literal["DisassociateMember"], Literal["CreateClassificationJob"], Literal["CreateCustomDataIdentifier"], Literal["UpdateMemberSession"], Literal["DescribeBuckets"], Literal["CreateFindingsFilter"], Literal["GetMember"], Literal["ListFindings"], Literal["GetMasterAccount"], Literal["UpdateClassificationJob"], Literal["GetSensitiveDataOccurrencesAvailability"], Literal["GetFindingStatistics"], Literal["UpdateOrganizationConfiguration"], Literal["EnableOrganizationAdminAccount"], Literal["UpdateMacieSession"], Literal["CreateAllowList"], Literal["PutFindingsPublicationConfiguration"], Literal["ListMembers"], Literal["GetFindingsPublicationConfiguration"], Literal["BatchGetCustomDataIdentifiers"], Literal["GetClassificationExportConfiguration"], Literal["UpdateClassificationScope"], Literal["GetClassificationScope"], Literal["CreateInvitations"], Literal["ListCustomDataIdentifiers"], Literal["GetCustomDataIdentifier"], Literal["GetUsageTotals"], Literal["ListOrganizationAdminAccounts"], Literal["DeleteInvitations"], Literal["GetSensitiveDataOccurrences"], Literal["UpdateSensitivityInspectionTemplate"], Literal["DisableMacie"], Literal["DeclineInvitations"], Literal["ListClassificationScopes"], Literal["UpdateAllowList"], Literal["EnableMacie"], Literal["UntagResource"], Literal["UpdateResourceProfile"], Literal["GetFindings"], Literal["DeleteAllowList"], Literal["DisableOrganizationAdminAccount"], Literal["GetAutomatedDiscoveryConfiguration"], Literal["SearchResources"], Literal["GetBucketStatistics"], Literal["GetMacieSession"], Literal["DeleteFindingsFilter"], Literal["ListTagsForResource"], Literal["TestCustomDataIdentifier"], Literal["GetRevealConfiguration"], Literal["DisassociateFromAdministratorAccount"], Literal["CreateMember"], Literal["ListInvitations"], Literal["GetSensitivityInspectionTemplate"], Literal["AcceptInvitation"], Literal["UpdateFindingsFilter"], Literal["ListManagedDataIdentifiers"], Literal["ListFindingsFilters"], Literal["DeleteCustomDataIdentifier"], Literal["ListClassificationJobs"]]
aws_macie2_condition_type = Union[Literal["aws:TagKeys"], Literal["aws:RequestTag/${TagKey}"]]

class aws_macie2Statement(GenericResourceType[aws_macie2_privilege_type, aws_macie2_condition_type]):
    def __init__(self, policy=None,  arns: List = [],  resources: List[AbstractTerraformResource] = None):
        super().__init__(policy, arns, resources)
    