from typing import Union, Literal, List
from hangar_sdk.core.rbac.aws.base_type import GenericResourceType
from hangar_sdk.resources.terraform import AbstractTerraformResource

aws_personalize_privilege_type = Union[Literal["GetSolutionMetrics"], Literal["ListCampaigns"], Literal["DescribeRecommender"], Literal["ListSolutions"], Literal["UpdateCampaign"], Literal["DescribeDatasetGroup"], Literal["DescribeMetricAttribution"], Literal["CreateDataset"], Literal["DeleteDatasetGroup"], Literal["DeleteMetricAttribution"], Literal["DescribeFilter"], Literal["DeleteEventTracker"], Literal["UpdateDataset"], Literal["PutEvents"], Literal["DeleteSchema"], Literal["ListRecipes"], Literal["CreateEventTracker"], Literal["ListDatasetExportJobs"], Literal["TagResource"], Literal["CreateBatchInferenceJob"], Literal["DescribeEventTracker"], Literal["CreateCampaign"], Literal["StartRecommender"], Literal["ListBatchInferenceJobs"], Literal["CreateFilter"], Literal["CreateRecommender"], Literal["PutActionInteractions"], Literal["UpdateRecommender"], Literal["DeleteFilter"], Literal["DescribeDatasetImportJob"], Literal["DescribeDataInsightsJob"], Literal["ListDataInsightsJobs"], Literal["CreateBatchSegmentJob"], Literal["PutItems"], Literal["CreateSolution"], Literal["CreateSchema"], Literal["CreateDatasetExportJob"], Literal["DeleteDataset"], Literal["DeleteRecommender"], Literal["CreateMetricAttribution"], Literal["DescribeDataset"], Literal["ListFilters"], Literal["GetActionRecommendations"], Literal["GetDataInsights"], Literal["DescribeFeatureTransformation"], Literal["StopRecommender"], Literal["DescribeBatchInferenceJob"], Literal["PutUsers"], Literal["DescribeRecipe"], Literal["ListBatchSegmentJobs"], Literal["GetRecommendations"], Literal["UpdateMetricAttribution"], Literal["ListDatasetGroups"], Literal["ListMetricAttributions"], Literal["DeleteCampaign"], Literal["DescribeBatchSegmentJob"], Literal["CreateDatasetGroup"], Literal["ListDatasetImportJobs"], Literal["DescribeCampaign"], Literal["DescribeSolutionVersion"], Literal["UntagResource"], Literal["ListRecommenders"], Literal["DeleteSolution"], Literal["StopSolutionVersionCreation"], Literal["CreateSolutionVersion"], Literal["ListEventTrackers"], Literal["DescribeDatasetExportJob"], Literal["DescribeSchema"], Literal["ListTagsForResource"], Literal["GetPersonalizedRanking"], Literal["ListSchemas"], Literal["PutActions"], Literal["ListMetricAttributionMetrics"], Literal["DescribeAlgorithm"], Literal["CreateDatasetImportJob"], Literal["CreateDataInsightsJob"], Literal["DescribeSolution"], Literal["ListDatasets"], Literal["ListSolutionVersions"]]
aws_personalize_condition_type = None

class aws_personalizeStatement(GenericResourceType[aws_personalize_privilege_type, aws_personalize_condition_type]):
    def __init__(self, policy=None,  arns: List = [],  resources: List[AbstractTerraformResource] = None):
        super().__init__(policy, arns, resources)
    