from typing import Union, Literal, List
from hangar_sdk.core.rbac.aws.base_type import GenericResourceType
from hangar_sdk.resources.terraform import AbstractTerraformResource

aws_opsworks_privilege_type = Union[Literal["SetTimeBasedAutoScaling"], Literal["DeregisterRdsDbInstance"], Literal["AssociateElasticIp"], Literal["UpdateLayer"], Literal["DescribeVolumes"], Literal["UntagResource"], Literal["DescribeRdsDbInstances"], Literal["CreateStack"], Literal["DeleteInstance"], Literal["DescribeElasticIps"], Literal["DescribeUserProfiles"], Literal["StopInstance"], Literal["UpdateUserProfile"], Literal["DeleteLayer"], Literal["CreateLayer"], Literal["ListTags"], Literal["GetHostnameSuggestion"], Literal["SetLoadBasedAutoScaling"], Literal["UpdateStack"], Literal["UpdateRdsDbInstance"], Literal["DescribeCommands"], Literal["RegisterElasticIp"], Literal["DescribeTimeBasedAutoScaling"], Literal["CreateDeployment"], Literal["DescribeMyUserProfile"], Literal["DeregisterVolume"], Literal["DeleteApp"], Literal["RegisterEcsCluster"], Literal["CreateUserProfile"], Literal["DescribeStackProvisioningParameters"], Literal["CreateApp"], Literal["DescribeDeployments"], Literal["GrantAccess"], Literal["AssignVolume"], Literal["AttachElasticLoadBalancer"], Literal["SetPermission"], Literal["AssignInstance"], Literal["DescribeApps"], Literal["DescribeEcsClusters"], Literal["StartStack"], Literal["DescribeStackSummary"], Literal["DeleteStack"], Literal["DescribeInstances"], Literal["DescribeAgentVersions"], Literal["UpdateApp"], Literal["DetachElasticLoadBalancer"], Literal["RegisterRdsDbInstance"], Literal["UpdateMyUserProfile"], Literal["DescribePermissions"], Literal["DeregisterEcsCluster"], Literal["DeleteUserProfile"], Literal["UpdateInstance"], Literal["CreateInstance"], Literal["DisassociateElasticIp"], Literal["StopStack"], Literal["RebootInstance"], Literal["DescribeRaidArrays"], Literal["UpdateVolume"], Literal["UnassignInstance"], Literal["StartInstance"], Literal["TagResource"], Literal["RegisterInstance"], Literal["RegisterVolume"], Literal["DescribeElasticLoadBalancers"], Literal["DescribeLoadBasedAutoScaling"], Literal["DescribeStacks"], Literal["DescribeServiceErrors"], Literal["DescribeOperatingSystems"], Literal["CloneStack"], Literal["UnassignVolume"], Literal["UpdateElasticIp"], Literal["DescribeLayers"], Literal["DeregisterElasticIp"], Literal["DeregisterInstance"]]
aws_opsworks_condition_type = None

class aws_opsworksStatement(GenericResourceType[aws_opsworks_privilege_type, aws_opsworks_condition_type]):
    def __init__(self, policy=None,  arns: List = [],  resources: List[AbstractTerraformResource] = None):
        super().__init__(policy, arns, resources)
    