from typing import Union, Literal, List
from hangar_sdk.core.rbac.aws.base_type import GenericResourceType
from hangar_sdk.resources.terraform import AbstractTerraformResource

aws_networkmanager_privilege_type = Union[Literal["DisassociateCustomerGateway"], Literal["UpdateLink"], Literal["ListCoreNetworkPolicyVersions"], Literal["CreateConnectPeer"], Literal["GetTransitGatewayConnectPeerAssociations"], Literal["AssociateCustomerGateway"], Literal["AcceptAttachment"], Literal["DeleteCoreNetworkPolicyVersion"], Literal["DisassociateConnectPeer"], Literal["DeleteGlobalNetwork"], Literal["GetCoreNetworkChangeEvents"], Literal["ListPeerings"], Literal["GetConnectAttachment"], Literal["DisassociateLink"], Literal["DeleteResourcePolicy"], Literal["GetConnectPeer"], Literal["TagResource"], Literal["CreateGlobalNetwork"], Literal["CreateVpcAttachment"], Literal["GetTransitGatewayPeering"], Literal["DeleteConnectPeer"], Literal["AssociateLink"], Literal["GetLinks"], Literal["CreateCoreNetwork"], Literal["GetLinkAssociations"], Literal["DeletePeering"], Literal["CreateTransitGatewayRouteTableAttachment"], Literal["GetCoreNetwork"], Literal["DeleteCoreNetwork"], Literal["GetTransitGatewayRouteTableAttachment"], Literal["AssociateTransitGatewayConnectPeer"], Literal["PutCoreNetworkPolicy"], Literal["CreateTransitGatewayPeering"], Literal["GetNetworkTelemetry"], Literal["DisassociateTransitGatewayConnectPeer"], Literal["StartRouteAnalysis"], Literal["AssociateConnectPeer"], Literal["ListCoreNetworks"], Literal["DeleteLink"], Literal["ListOrganizationServiceAccessStatus"], Literal["DeleteSite"], Literal["UpdateCoreNetwork"], Literal["UpdateGlobalNetwork"], Literal["DeleteAttachment"], Literal["GetCoreNetworkPolicy"], Literal["DescribeGlobalNetworks"], Literal["GetNetworkRoutes"], Literal["UpdateVpcAttachment"], Literal["ListAttachments"], Literal["UpdateSite"], Literal["DeleteConnection"], Literal["GetDevices"], Literal["GetNetworkResources"], Literal["ListConnectPeers"], Literal["CreateLink"], Literal["CreateSite"], Literal["PutResourcePolicy"], Literal["StartOrganizationServiceAccessUpdate"], Literal["ExecuteCoreNetworkChangeSet"], Literal["CreateSiteToSiteVpnAttachment"], Literal["GetSiteToSiteVpnAttachment"], Literal["GetTransitGatewayRegistrations"], Literal["GetRouteAnalysis"], Literal["UpdateNetworkResourceMetadata"], Literal["GetConnections"], Literal["GetResourcePolicy"], Literal["GetConnectPeerAssociations"], Literal["RejectAttachment"], Literal["UntagResource"], Literal["UpdateDevice"], Literal["RestoreCoreNetworkPolicyVersion"], Literal["GetNetworkResourceCounts"], Literal["CreateConnection"], Literal["UpdateConnection"], Literal["ListTagsForResource"], Literal["DeleteDevice"], Literal["DeregisterTransitGateway"], Literal["CreateConnectAttachment"], Literal["GetCustomerGatewayAssociations"], Literal["GetNetworkResourceRelationships"], Literal["GetVpcAttachment"], Literal["GetSites"], Literal["GetCoreNetworkChangeSet"], Literal["CreateDevice"], Literal["RegisterTransitGateway"]]
aws_networkmanager_condition_type = Union[Literal["aws:TagKeys"], Literal["networkmanager:subnetArns"], Literal["aws:ResourceTag/${TagKey}"], Literal["networkmanager:tgwRtbArn"], Literal["networkmanager:vpnConnectionArn"], Literal["networkmanager:cgwArn"], Literal["networkmanager:tgwConnectPeerArn"], Literal["networkmanager:vpcArn"], Literal["networkmanager:tgwArn"], Literal["aws:RequestTag/${TagKey}"]]

class aws_networkmanagerStatement(GenericResourceType[aws_networkmanager_privilege_type, aws_networkmanager_condition_type]):
    def __init__(self, policy=None,  arns: List = [],  resources: List[AbstractTerraformResource] = None):
        super().__init__(policy, arns, resources)
    