from typing import Union, Literal, List
from hangar_sdk.core.rbac.aws.base_type import GenericResourceType
from hangar_sdk.resources.terraform import AbstractTerraformResource

aws_bedrock_privilege_type = Union[Literal["CreateAgent"], Literal["InvokeAgent"], Literal["StopModelCustomizationJob"], Literal["UpdateDataSource"], Literal["CreateGuardrail"], Literal["GetFoundationModelAvailability"], Literal["ListIngestionJobs"], Literal["CreateModelInvocationJob"], Literal["GetAgentKnowledgeBase"], Literal["CreateKnowledgeBase"], Literal["GetAgent"], Literal["Retrieve"], Literal["InvokeModelWithResponseStream"], Literal["GetModelInvocationLoggingConfiguration"], Literal["GetAgentActionGroup"], Literal["ListProvisionedModelThroughputs"], Literal["CreateProvisionedModelThroughput"], Literal["TagResource"], Literal["DeleteGuardrail"], Literal["ListKnowledgeBases"], Literal["GetCustomModel"], Literal["CreateAgentAlias"], Literal["UpdateAgentKnowledgeBase"], Literal["UpdateAgent"], Literal["GetFoundationModel"], Literal["CreateFoundationModelAgreement"], Literal["GetModelEvaluationJob"], Literal["ListModelEvaluationJobs"], Literal["ListDataSources"], Literal["GetAgentAlias"], Literal["ListFoundationModelAgreementOffers"], Literal["DeleteFoundationModelAgreement"], Literal["UpdateProvisionedModelThroughput"], Literal["AssociateThirdPartyKnowledgeBase"], Literal["PrepareAgent"], Literal["ListAgentKnowledgeBases"], Literal["ListAgents"], Literal["DeleteModelInvocationLoggingConfiguration"], Literal["StartIngestionJob"], Literal["UpdateKnowledgeBase"], Literal["ListAgentAliases"], Literal["GetUseCaseForModelAccess"], Literal["ListGuardrails"], Literal["GetIngestionJob"], Literal["InvokeModel"], Literal["CreateModelEvaluationJob"], Literal["DeleteCustomModel"], Literal["GetDataSource"], Literal["GetProvisionedModelThroughput"], Literal["PutModelInvocationLoggingConfiguration"], Literal["ListAgentActionGroups"], Literal["CreateDataSource"], Literal["UpdateAgentAlias"], Literal["UpdateGuardrail"], Literal["ListCustomModels"], Literal["GetModelCustomizationJob"], Literal["ListModelCustomizationJobs"], Literal["RetrieveAndGenerate"], Literal["UpdateAgentActionGroup"], Literal["DeleteDataSource"], Literal["ListAgentVersions"], Literal["UntagResource"], Literal["ListFoundationModels"], Literal["GetModelInvocationJob"], Literal["ListModelInvocationJobs"], Literal["DeleteKnowledgeBase"], Literal["PutUseCaseForModelAccess"], Literal["DeleteAgentVersion"], Literal["DeleteAgentAlias"], Literal["DeleteAgentActionGroup"], Literal["ListTagsForResource"], Literal["AssociateAgentKnowledgeBase"], Literal["StopModelInvocationJob"], Literal["CreateModelCustomizationJob"], Literal["PutFoundationModelEntitlement"], Literal["CreateAgentActionGroup"], Literal["DisassociateAgentKnowledgeBase"], Literal["CreateGuardrailVersion"], Literal["DeleteAgent"], Literal["GetAgentVersion"], Literal["DeleteProvisionedModelThroughput"], Literal["GetKnowledgeBase"], Literal["GetGuardrail"]]
aws_bedrock_condition_type = Union[Literal["aws:TagKeys"], Literal["bedrock:ThirdPartyKnowledgeBaseCredentialsSecretArn"], Literal["aws:RequestTag/${TagKey}"]]

class aws_bedrockStatement(GenericResourceType[aws_bedrock_privilege_type, aws_bedrock_condition_type]):
    def __init__(self, policy=None,  arns: List = [],  resources: List[AbstractTerraformResource] = None):
        super().__init__(policy, arns, resources)
    