from typing import Union, Literal, List
from hangar_sdk.core.rbac.aws.base_type import GenericResourceType
from hangar_sdk.resources.terraform import AbstractTerraformResource

aws_imagebuilder_privilege_type = Union[Literal["ListLifecycleExecutions"], Literal["ListDistributionConfigurations"], Literal["ImportVmImage"], Literal["UntagResource"], Literal["DeleteImage"], Literal["GetComponent"], Literal["ListContainerRecipes"], Literal["ListImagePipelineImages"], Literal["ListImagePipelines"], Literal["DeleteImagePipeline"], Literal["PutComponentPolicy"], Literal["ListImageScanFindings"], Literal["CreateImageRecipe"], Literal["GetWorkflowStepExecution"], Literal["UpdateDistributionConfiguration"], Literal["DeleteInfrastructureConfiguration"], Literal["PutContainerRecipePolicy"], Literal["CreateDistributionConfiguration"], Literal["GetImagePipeline"], Literal["DeleteDistributionConfiguration"], Literal["ListImageRecipes"], Literal["ListWorkflows"], Literal["StartImagePipelineExecution"], Literal["GetLifecyclePolicy"], Literal["GetImagePolicy"], Literal["SendWorkflowStepAction"], Literal["UpdateImagePipeline"], Literal["UpdateInfrastructureConfiguration"], Literal["GetContainerRecipePolicy"], Literal["ListComponentBuildVersions"], Literal["ListWaitingWorkflowSteps"], Literal["CreateLifecyclePolicy"], Literal["GetLifecycleExecution"], Literal["DeleteContainerRecipe"], Literal["StartResourceStateUpdate"], Literal["DeleteWorkflow"], Literal["GetImageRecipe"], Literal["ListTagsForResource"], Literal["CancelLifecycleExecution"], Literal["GetImageRecipePolicy"], Literal["ListImageBuildVersions"], Literal["DeleteComponent"], Literal["DeleteLifecyclePolicy"], Literal["ListLifecyclePolicies"], Literal["GetContainerRecipe"], Literal["CancelImageCreation"], Literal["ListImageScanFindingAggregations"], Literal["CreateInfrastructureConfiguration"], Literal["ListWorkflowStepExecutions"], Literal["PutImageRecipePolicy"], Literal["ListWorkflowExecutions"], Literal["ListWorkflowBuildVersions"], Literal["GetImage"], Literal["ImportComponent"], Literal["CreateContainerRecipe"], Literal["ListComponents"], Literal["ListInfrastructureConfigurations"], Literal["GetInfrastructureConfiguration"], Literal["GetWorkflow"], Literal["CreateComponent"], Literal["ListImagePackages"], Literal["ListImages"], Literal["CreateImage"], Literal["CreateImagePipeline"], Literal["ListLifecycleExecutionResources"], Literal["TagResource"], Literal["CreateWorkflow"], Literal["GetDistributionConfiguration"], Literal["GetWorkflowExecution"], Literal["GetComponentPolicy"], Literal["DeleteImageRecipe"], Literal["PutImagePolicy"], Literal["UpdateLifecyclePolicy"]]
aws_imagebuilder_condition_type = Union[Literal["aws:TagKeys"], Literal["imagebuilder:CreatedResourceTagKeys"], Literal["imagebuilder:LifecyclePolicyResourceType"], Literal["aws:ResourceTag/${TagKey}"], Literal["imagebuilder:CreatedResourceTag/<key>"], Literal["imagebuilder:StatusTopicArn"], Literal["imagebuilder:Ec2MetadataHttpTokens"], Literal["aws:RequestTag/${TagKey}"]]

class aws_imagebuilderStatement(GenericResourceType[aws_imagebuilder_privilege_type, aws_imagebuilder_condition_type]):
    def __init__(self, policy=None,  arns: List = [],  resources: List[AbstractTerraformResource] = None):
        super().__init__(policy, arns, resources)
    