from typing import Union, Literal, List
from hangar_sdk.core.rbac.aws.base_type import GenericResourceType
from hangar_sdk.resources.terraform import AbstractTerraformResource

aws_autoscaling_privilege_type = Union[Literal["DeletePolicy"], Literal["DescribeTrafficSources"], Literal["CompleteLifecycleAction"], Literal["DescribeNotificationConfigurations"], Literal["DescribeScheduledActions"], Literal["DescribeAdjustmentTypes"], Literal["DescribeWarmPool"], Literal["PutLifecycleHook"], Literal["PutScalingPolicy"], Literal["RecordLifecycleActionHeartbeat"], Literal["DeleteWarmPool"], Literal["ExecutePolicy"], Literal["CancelInstanceRefresh"], Literal["DescribeTags"], Literal["SetInstanceProtection"], Literal["DetachLoadBalancerTargetGroups"], Literal["AttachLoadBalancers"], Literal["DescribeScalingProcessTypes"], Literal["CreateOrUpdateTags"], Literal["DescribeAccountLimits"], Literal["CreateAutoScalingGroup"], Literal["DeleteTags"], Literal["AttachLoadBalancerTargetGroups"], Literal["SetDesiredCapacity"], Literal["DescribeScalingActivities"], Literal["GetPredictiveScalingForecast"], Literal["CreateLaunchConfiguration"], Literal["StartInstanceRefresh"], Literal["ExitStandby"], Literal["SuspendProcesses"], Literal["DeleteLaunchConfiguration"], Literal["DisableMetricsCollection"], Literal["PutScheduledUpdateGroupAction"], Literal["PutWarmPool"], Literal["RollbackInstanceRefresh"], Literal["DescribeInstanceRefreshes"], Literal["DescribeLifecycleHooks"], Literal["DeleteScheduledAction"], Literal["DetachTrafficSources"], Literal["DescribeLoadBalancerTargetGroups"], Literal["DescribeLoadBalancers"], Literal["EnterStandby"], Literal["DescribeTerminationPolicyTypes"], Literal["BatchDeleteScheduledAction"], Literal["UpdateAutoScalingGroup"], Literal["DeleteLifecycleHook"], Literal["AttachInstances"], Literal["DescribeLifecycleHookTypes"], Literal["SetInstanceHealth"], Literal["TerminateInstanceInAutoScalingGroup"], Literal["BatchPutScheduledUpdateGroupAction"], Literal["DescribeLaunchConfigurations"], Literal["ResumeProcesses"], Literal["DeleteAutoScalingGroup"], Literal["PutNotificationConfiguration"], Literal["DescribeAutoScalingGroups"], Literal["DescribeMetricCollectionTypes"], Literal["DetachLoadBalancers"], Literal["EnableMetricsCollection"], Literal["DescribeAutoScalingNotificationTypes"], Literal["AttachTrafficSources"], Literal["DeleteNotificationConfiguration"], Literal["DetachInstances"], Literal["DescribeAutoScalingInstances"], Literal["DescribePolicies"]]
aws_autoscaling_condition_type = Union[Literal["autoscaling:MetadataHttpEndpoint"], Literal["autoscaling:MaxSize"], Literal["autoscaling:LoadBalancerNames"], Literal["autoscaling:TrafficSourceIdentifiers"], Literal["autoscaling:MinSize"], Literal["autoscaling:LaunchTemplateVersionSpecified"], Literal["aws:TagKeys"], Literal["autoscaling:SpotPrice"], Literal["autoscaling:LaunchConfigurationName"], Literal["autoscaling:InstanceType"], Literal["autoscaling:InstanceTypes"], Literal["autoscaling:VPCZoneIdentifiers"], Literal["autoscaling:ImageId"], Literal["autoscaling:ResourceTag/${TagKey}"], Literal["autoscaling:MetadataHttpTokens"], Literal["autoscaling:TargetGroupARNs"], Literal["aws:ResourceTag/${TagKey}"], Literal["autoscaling:MetadataHttpPutResponseHopLimit"], Literal["aws:RequestTag/${TagKey}"]]

class aws_autoscalingStatement(GenericResourceType[aws_autoscaling_privilege_type, aws_autoscaling_condition_type]):
    def __init__(self, policy=None,  arns: List = [],  resources: List[AbstractTerraformResource] = None):
        super().__init__(policy, arns, resources)
    