from typing import Union, Literal, List
from hangar_sdk.core.rbac.aws.base_type import GenericResourceType
from hangar_sdk.resources.terraform import AbstractTerraformResource

aws_cloudformation_privilege_type = Union[Literal["DescribeStackResourceDrifts"], Literal["GetTemplateSummary"], Literal["DescribeStackInstance"], Literal["GetTemplate"], Literal["UpdateStack"], Literal["DescribeChangeSet"], Literal["SetTypeConfiguration"], Literal["ImportStacksToStackSet"], Literal["ListStackSetOperationResults"], Literal["CancelResourceRequest"], Literal["DescribeStackEvents"], Literal["DescribeStackResources"], Literal["GetResource"], Literal["ValidateTemplate"], Literal["DetectStackResourceDrift"], Literal["TagResource"], Literal["SignalResource"], Literal["ExecuteChangeSet"], Literal["GetResourceRequestStatus"], Literal["ListStackInstanceResourceDrifts"], Literal["CreateStack"], Literal["DescribeStackSet"], Literal["DeactivateType"], Literal["ListExports"], Literal["BatchDescribeTypeConfigurations"], Literal["CreateChangeSet"], Literal["DescribeTypeRegistration"], Literal["GetStackPolicy"], Literal["ActivateType"], Literal["DeactivateOrganizationsAccess"], Literal["DeleteStack"], Literal["DescribePublisher"], Literal["ListTypeVersions"], Literal["DescribeOrganizationsAccess"], Literal["CreateResource"], Literal["ContinueUpdateRollback"], Literal["ListImports"], Literal["SetTypeDefaultVersion"], Literal["RecordHandlerProgress"], Literal["DeregisterType"], Literal["RegisterPublisher"], Literal["CancelUpdateStack"], Literal["ListStackResources"], Literal["UpdateTerminationProtection"], Literal["ListResources"], Literal["RegisterType"], Literal["DescribeAccountLimits"], Literal["RollbackStack"], Literal["DeleteStackSet"], Literal["ListStackInstances"], Literal["DescribeChangeSetHooks"], Literal["DeleteResource"], Literal["CreateStackInstances"], Literal["UpdateStackSet"], Literal["ActivateOrganizationsAccess"], Literal["ListChangeSets"], Literal["ListStacks"], Literal["DescribeStacks"], Literal["DetectStackSetDrift"], Literal["EstimateTemplateCost"], Literal["PublishType"], Literal["UpdateResource"], Literal["DetectStackDrift"], Literal["UntagResource"], Literal["CreateUploadBucket"], Literal["TestType"], Literal["ListStackSetOperations"], Literal["ListTypeRegistrations"], Literal["CreateStackSet"], Literal["DescribeStackDriftDetectionStatus"], Literal["SetStackPolicy"], Literal["ListStackSets"], Literal["StopStackSetOperation"], Literal["ListResourceRequests"], Literal["DescribeType"], Literal["DescribeStackResource"], Literal["UpdateStackInstances"], Literal["ListTypes"], Literal["DescribeStackSetOperation"], Literal["DeleteStackInstances"], Literal["DeleteChangeSet"]]
aws_cloudformation_condition_type = Union[Literal["aws:TagKeys"], Literal["cloudformation:TemplateUrl"], Literal["cloudformation:TargetRegion"], Literal["cloudformation:ImportResourceTypes"], Literal["cloudformation:ChangeSetName"], Literal["cloudformation:StackPolicyUrl"], Literal["cloudformation:ResourceTypes"], Literal["cloudformation:RoleArn"], Literal["aws:RequestTag/${TagKey}"]]

class aws_cloudformationStatement(GenericResourceType[aws_cloudformation_privilege_type, aws_cloudformation_condition_type]):
    def __init__(self, policy=None,  arns: List = [],  resources: List[AbstractTerraformResource] = None):
        super().__init__(policy, arns, resources)
    