from typing import Union, Literal, List
from hangar_sdk.core.rbac.aws.base_type import GenericResourceType
from hangar_sdk.resources.terraform import AbstractTerraformResource

aws_clouddirectory_privilege_type = Union[Literal["ListObjectAttributes"], Literal["UntagResource"], Literal["CreateObject"], Literal["PutSchemaFromJson"], Literal["DetachObject"], Literal["RemoveFacetFromObject"], Literal["ListObjectPolicies"], Literal["ListDirectories"], Literal["ListAppliedSchemaArns"], Literal["GetFacet"], Literal["PublishSchema"], Literal["AttachPolicy"], Literal["ListFacetAttributes"], Literal["AddFacetToObject"], Literal["ListTypedLinkFacetNames"], Literal["LookupPolicy"], Literal["CreateIndex"], Literal["CreateDirectory"], Literal["EnableDirectory"], Literal["DisableDirectory"], Literal["ListObjectParents"], Literal["ListObjectChildren"], Literal["DeleteObject"], Literal["GetLinkAttributes"], Literal["ListIncomingTypedLinks"], Literal["ListTypedLinkFacetAttributes"], Literal["ListManagedSchemaArns"], Literal["DetachPolicy"], Literal["DeleteDirectory"], Literal["GetDirectory"], Literal["GetObjectInformation"], Literal["ListTagsForResource"], Literal["UpdateObjectAttributes"], Literal["ListIndex"], Literal["ListFacetNames"], Literal["DetachFromIndex"], Literal["DeleteTypedLinkFacet"], Literal["ListOutgoingTypedLinks"], Literal["BatchWrite"], Literal["UpdateFacet"], Literal["CreateFacet"], Literal["ApplySchema"], Literal["DeleteSchema"], Literal["UpdateTypedLinkFacet"], Literal["ListAttachedIndices"], Literal["GetAppliedSchemaVersion"], Literal["GetSchemaAsJson"], Literal["ListObjectParentPaths"], Literal["ListPublishedSchemaArns"], Literal["AttachTypedLink"], Literal["UpgradePublishedSchema"], Literal["UpdateSchema"], Literal["UpdateLinkAttributes"], Literal["ListDevelopmentSchemaArns"], Literal["ListPolicyAttachments"], Literal["UpgradeAppliedSchema"], Literal["BatchRead"], Literal["GetTypedLinkFacetInformation"], Literal["TagResource"], Literal["DetachTypedLink"], Literal["CreateSchema"], Literal["GetObjectAttributes"], Literal["CreateTypedLinkFacet"], Literal["AttachToIndex"], Literal["DeleteFacet"], Literal["AttachObject"]]
aws_clouddirectory_condition_type = None

class aws_clouddirectoryStatement(GenericResourceType[aws_clouddirectory_privilege_type, aws_clouddirectory_condition_type]):
    def __init__(self, policy=None,  arns: List = [],  resources: List[AbstractTerraformResource] = None):
        super().__init__(policy, arns, resources)
    