from typing import Union, Literal, List
from hangar_sdk.core.rbac.aws.base_type import GenericResourceType
from hangar_sdk.resources.terraform import AbstractTerraformResource

aws_iotsitewise_privilege_type = Union[Literal["BatchPutAssetPropertyValue"], Literal["CreateAsset"], Literal["EnableSiteWiseIntegration"], Literal["GetAssetPropertyValueHistory"], Literal["ListTimeSeries"], Literal["CreateAssetModelCompositeModel"], Literal["DescribeStorageConfiguration"], Literal["DescribeAction"], Literal["GetInterpolatedAssetPropertyValues"], Literal["UpdatePortal"], Literal["DescribeAsset"], Literal["ListAssetModelProperties"], Literal["ListAccessPolicies"], Literal["ListAssetProperties"], Literal["UpdateProject"], Literal["DescribeGateway"], Literal["DisassociateTimeSeriesFromAssetProperty"], Literal["ListAssociatedAssets"], Literal["ListDashboards"], Literal["TagResource"], Literal["CreateBulkImportJob"], Literal["CreateProject"], Literal["DescribeAssetCompositeModel"], Literal["DescribeLoggingOptions"], Literal["ListAssetModelCompositeModels"], Literal["PutDefaultEncryptionConfiguration"], Literal["CreatePortal"], Literal["UpdateAssetProperty"], Literal["UpdateAsset"], Literal["ListProjects"], Literal["DescribeTimeSeries"], Literal["BatchGetAssetPropertyValue"], Literal["BatchDisassociateProjectAssets"], Literal["UpdateAccessPolicy"], Literal["DescribeBulkImportJob"], Literal["ListActions"], Literal["ExecuteQuery"], Literal["CreateAccessPolicy"], Literal["DeleteProject"], Literal["ListGateways"], Literal["DescribePortal"], Literal["GetAssetPropertyAggregates"], Literal["PutStorageConfiguration"], Literal["DescribeAssetProperty"], Literal["BatchGetAssetPropertyValueHistory"], Literal["DeleteAsset"], Literal["ListCompositionRelationships"], Literal["DeletePortal"], Literal["CreateDashboard"], Literal["AssociateAssets"], Literal["UpdateGatewayCapabilityConfiguration"], Literal["AssociateTimeSeriesToAssetProperty"], Literal["ExecuteAction"], Literal["DescribeDashboard"], Literal["DescribeAccessPolicy"], Literal["UpdateAssetModelPropertyRouting"], Literal["ListAssetRelationships"], Literal["DeleteAssetModelCompositeModel"], Literal["DeleteGateway"], Literal["DescribeAssetModelCompositeModel"], Literal["DescribeDefaultEncryptionConfiguration"], Literal["DescribeProject"], Literal["ListAssets"], Literal["PutLoggingOptions"], Literal["UpdateAssetModel"], Literal["UntagResource"], Literal["CreateAssetModel"], Literal["ListPortals"], Literal["DeleteDashboard"], Literal["BatchAssociateProjectAssets"], Literal["UpdateAssetModelCompositeModel"], Literal["ListProjectAssets"], Literal["DescribeAssetModel"], Literal["DeleteAssetModel"], Literal["UpdateDashboard"], Literal["DisassociateAssets"], Literal["ListTagsForResource"], Literal["DescribeGatewayCapabilityConfiguration"], Literal["BatchGetAssetPropertyAggregates"], Literal["CreateGateway"], Literal["GetAssetPropertyValue"], Literal["UpdateGateway"], Literal["ListAssetModels"], Literal["DeleteTimeSeries"], Literal["DeleteAccessPolicy"], Literal["ListBulkImportJobs"]]
aws_iotsitewise_condition_type = Union[Literal["aws:TagKeys"], Literal["aws:ResourceTag/${TagKey}"], Literal["aws:RequestTag/${TagKey}"]]

class aws_iotsitewiseStatement(GenericResourceType[aws_iotsitewise_privilege_type, aws_iotsitewise_condition_type]):
    def __init__(self, policy=None,  arns: List = [],  resources: List[AbstractTerraformResource] = None):
        super().__init__(policy, arns, resources)
    